FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Inmar Consumer Extension (ICE) API v1

In an effort to abstract the DPN APIs, the new consumer web projects will utilize a middle-ware that is designed to return data in a way that is faster and more compatible with modern web applications.
These APIs are designed to be RESTful and return only the data required by the application display layer.

The API provides some key benefits for enhanced web and mobile application UX including:

- Keyword searching of offers
- Category counting/filtering
- User statistics - including rank and lifetime savings with a breakdown by month Badge support to tag recommended, new and expiring offers

**The API currently does not support the OPTION header with CORS. All POST requests should include parameters in the x-www-form-urlencoded form with no custom headers.**

*In the document below replace the <api_url> tag with the appropriate instance of the API being used, for example replace <api url> with ice.test.dpn.inmar.com for the demo test API.*

# Group User APIs

## Login [/login]

### Login [POST]

`https://<api_url>/login`

**`Origin` header is required for this request.**

The Login resource has the following (x-www-form-urlencoded) attributes:

- **username** : Loyalty ID or Email Address of user (required)

- **password** : Clear-text password (required)

Response contains `token` which should be used for any subsequent contextual user API calls. 

Token identifies the user; may or may not expire depending on API setup.

+ Request (application/json)

    + Headers

            Origin: http://www.example-social-network.com
            
    + Body

            {
                "username" : "lilypad76",
                "password" : "mycatsname"
            }

+ Response 200 (application/json)

        { "token": "XXXXXXXXXXX" }
    
+ Response 401

        Login failed; user or password is invalid

+ Response 500

        Some other error occurred, DPN service likely unavailable
        
## Register [/register]

### Register [POST]

`https://<api_url>/register`

**`Origin` header is required for this request.**

The Register resource has the following (x-www-form-urlencoded) attributes:

- **username** : Loyalty ID, default is 11 digits but may be variable depending on customer (required)

- **password** : Clear-text password (required)

- **email** : Email address of the customer (required)

Response contains `token` which should be used for any subsequent contextual user API calls. 

Token identifies the user; may or may not expire depending on API setup.

+ Request (application/json)

    + Headers

            Origin: http://www.example-social-network.com
            
    + Body
        
            {
                "username" : "lilypad76",
                "password" : "mycatsname",
                "email" : "lily@catsmeow.com"
            }
        
+ Response 200 (application/json)

        { "token": "XXXXXXXXXXX" }

+ Response 400

        Missing either username, password, or email
        
+ Response 409

        Either the user or email address is already registered in the system

+ Response 500

        Some other error occurred, DPN service likely unavailable
        
## User Info [/userinfo{?token}]

### User Info [GET]

`https://<api_url>/userinfo?token={token}`

+ Parameters
    + token (required, string) ... User token of the customer

+ Response 200

        {
            "zip": "43402",
            "firstName": "John",
            "lastName": "Customer",
            "email": "john.q@customer.com",
            "phone": "555-555-1212",
            "address1": "4000 Park Ave.",
            "address2": "Apt. 1b",
            "city": "Cleveland",
            "state": "OH",
            "loyaltyId": "1234323456",
            "metadata": {
                "emailoptin": "none"
            },
            "profileComplete": true
        }
    
+ Response 401

        Token is invalid

+ Response 500

        Some other error occurred, DPN service likely unavailable
        
### User Info [POST]

`https://<api_url>/userinfo`

The User Info resource has the following (x-www-form-urlencoded) attributes:

- **token** : User token of the customer (Required)
- **email** : Email address of the customer (not validated on the server, client should perform format check)
- **firstname** : First name of the customer
- **lastname** : Last name of the customer
- **phone** : Phone number of the customer (not settable if this is the primary ID for the retailer - use userid API)
- **address1** : Street address (field 1)
- **address2** : Street address (field 2)
- **city** : City
- **state** : State
- **zip** : Postal code (10 digit max)
- **emailoptin** : Customer Email preference (accepted values: "specific", "none")

+ Request (application/json)

        {
            "token": "XXXXXXXXXXXX",
            "zip": "43402",
            "firstName": "John",
            "lastName": "Customer",
            "email": "john.q@customer.com",
            "phone": "555-555-1212",
            "address1": "4000 Park Ave.",
            "address2": "Apt. 1b",
            "city": "Cleveland",
            "state": "OH",
            "loyaltyId": "1234323456",
            "emailoptin": "none"
        }

+ Response 200 (application/json)

        {
            "zip": "43402",
            "firstName": "John",
            "lastName": "Customer",
            "email": "john.q@customer.com",
            "phone": "555-555-1212",
            "address1": "4000 Park Ave.",
            "address2": "Apt. 1b",
            "city": "Cleveland",
            "state": "OH",
            "loyaltyId": "1234323456",
            "metadata": {
                "emailoptin": "none"
            },
            "profileComplete": true
        }
    
    
+ Response 400
        
        Input XML is empty or malformed.

+ Response 500 

        An unexpected error has occurred: {x}

+ Response 400 

        Missing required tag 'Name'.
        
+ Response 409
        
        A customer with this Phone already exists.

+ Response 409
        
        A customer with this LoyaltyID already exists.

+ Response 409  
        
        A customer with this Alternate ID already exists.

+ Response 409 

        A customer with this Email already exists.
        
## User Id [/userid{?token}]

### User Id [GET]

`https://<api_url>/userid?token={token}`

Response differs by retailer "type":

- *Loyalty* based retailers return:
    
        { "loyaltyId" : "123456789" }

- *Phone* based retailers return:
    
        { "phone" : "555-555-1212" }

+ Parameters
    + token (required, string) ... User token of the customer
    
+ Response 200 (application/json)

        { "loyaltyId" : "123456789" }
        
+ Response 200 (application/json)

        { "phone" : "555-555-1212" }
        
### User Id [POST]

`https://<api_url>/userid`

The User Id resource has the following (x-www-form-urlencoded) attributes:

- **token** : User token of the customer (Required)
- **userID** : New user ID for the customer (Required)

Response contains `token` which should be used for any subsequent contextual user API calls. 

Token identifies the user; may or may not expire depending on API setup.

+ Request (application/json)

        {
            "token": "XXXXXXXXXXXXX",
            "userId": "c2ztS9Kuoz"
        }
            
+ Response 200 (application/json)

        { "token": "XXXXXXXXXXXXX" }
        
## User Password [/userpass]

### User Password [POST]

`https://<api_url>/userpass`

The User Password resource has the following (x-www-form-urlencoded) attributes:

- **token** : User token of the customer (Required)
- **current** : Current password of the customer (Required)
- **updated** : New password for the customer (Required)

Response contains `token` which should be used for any subsequent contextual user API calls. 

Token identifies the user; may or may not expire depending on API setup.
            
+ Request (application/json)

        {
            "token": "XXXXXXXXXXXXX",
            "current": "123456789",
            "updated": "c2ztS9Kuoz",
        }
    
+ Response 200 (application/json)

        { "token": "XXXXXXXXXXXXX" }
        
+ Response 400

        Bad input paramter
        
+ Response 401

        Not authenticated (e.g. token expired)
        
## Forgot Password [/userforgot]

### Forgot Password [POST]

`https://<api_url>/userforgot`

The Forgot Password resource has the following (x-www-form-urlencoded) attributes:

- **email** : Customer E-mail Address (Required)

No response; sends an e-mail to the account holder with instructions and a link to reset their password.

+ Request (application/json)

        {"email": "john.q@customer.com"}

+ Response 200

+ Response 400

        Bad input paramter
        
## Reset Password [/userreset]

### Reset Password [POST]

`https://<api_url>/userreset`

**`Origin` header is required for this request.**

The Reset Password resource has the following (x-www-form-urlencoded) attributes:

- **resetToken** : Valid reset token (Required)
- **updated** : New password for the customer (Required)

Response contains `token` which should be used for any subsequent contextual user API calls. 

Token identifies the user; may or may not expire depending on API setup.

+ Request (application/json)

    + Headers

            Origin: http://www.example-social-network.com
            
    + Body

            {
                "resetToken": "kjfad8faus8fuapfuada9f7fa"
                "updated": "c2ztS9Kuoz",
            }
            
+ Response 200 (application/json)

        { "token": "XXXXXXXXXXXXX" }
        
+ Response 400

        Invalid / Expired Token
        
## User Stats [/userstats{?token}]

### User Stats [GET]

`https://<api_url>/userstats?token={token}`

The response object may or may not contain all these parameters depending on what statistics are available for user.

**Normal Response:**
            
    {   
        "savingsThisYear": 10050,
        "savingsLastTwelveMonths": 40200,
        "lifetimeSavings": 76525,
        "averageMonthlySavings": 3375,
        "rank": 15,
        "saverType": "bottom",
        "recommended": {
            "missed": 65,
            "expired": 65
        },
        "monthlySavings": [
            {
                "month": 1,
                "value": 3375,
                "year": 2014
            },
            {
                "month": 2,
                "value": 2433,
                "year": 2014
            },
            {
                "month": 3,
                "value": 4100,
                "year": 2014
            },
            {
                "month": 4,
                "value": 4673,
                "year": 2014
            },
            {
                "month": 5,
                "value": 3375,
                "year": 2014
            }
        ],
        "updatedDate": "2014-06-26T16:41:00.007Z"
    }
        
**Minimum Response (No analytics for the user):**
            
    { "lifetimeSavings": 0 }
    
+ Parameters
    + token (required, string) ... token returned from Login or Register
    
+ Response 200 (application/json)

            {   
                "savingsThisYear": 10050,
                "savingsLastTwelveMonths": 40200,
                "lifetimeSavings": 76525,
                "averageMonthlySavings": 3375,
                "rank": 15,
                "saverType": "bottom",
                "recommended": {
                    "missed": 65,
                    "expired": 65
                },
                "monthlySavings": [
                {
                    "month": 1,
                    "value": 3375,
                    "year": 2014
                },
                {
                    "month": 2,
                    "value": 2433,
                    "year": 2014
                },
                {
                    "month": 3,
                    "value": 4100,
                    "year": 2014
                },
                {
                    "month": 4,
                    "value": 4673,
                    "year": 2014
                },
                {
                    "month": 5,
                    "value": 3375,
                    "year": 2014
                }
            ],
            "updatedDate": "2014-06-26T16:41:00.007Z"
        }
        
+ Response 200 (application/json)

            { "lifetimeSavings": 0 }
            
+ Response 401

        Token is invalid

+ Response 500

        An unexpected error has occurred

## Wallet [/wallet{?token}]

### Wallet [GET]

`https://<api_url>/wallet?token={token}`

+ Parameters
    + token (required, string) ... token returned from Login or Register
            
+ Response 200 (application/json)

            {
                "clippedCount": 78,
                "clippedValue": 65.02
                "profileComplete" : true
            }

+ Response 401

        Token is invalid

+ Response 500

        Some other error occurred, DPN service likely unavailable, or something was wrong with the parameters provided.
        
## Email Shopping List [/emailshoplist]

### Email Shopping List [POST]

`https://<api_url>/emailshoplist`

The Email Shopping List resource has the following (x-www-form-urlencoded) attributes:

- **token** : User token of the customer (Required)

+ Request (application/json)

        { "token": "XXXXXXXXXXXXX" }
        
+ Response 200 (application/json)

        {
            "email": "john.q@customer.com"
        }
            
+ Response 400

        Bad Request

+ Response 500

        Some other error occurred, DPN service likely unavailable

# Group Offer APIs

## Offers [/offers{?skip,clipped,keywords,limit,categories,sort,redeemed,expired,includeClipped}]

### Offers [GET]

`https://<api_url>/offers?<Optional Parameters>`

+ Parameters
    + skip (optional, number) ... skip specified number of offers
    + clipped (optional, boolean) ... set to `true` to return a user's clipped offers only
    + keywords (optional, string, `baby,food`) ... a comma delimited list of keywords to search offers for
    + limit = `12` (optional, number)  ... limit to n number of offers
    + categories (optional, string) ... comma delimited list of category keys, default is offers from all categories
    + sort (optional, string) ... string for sort order, one of the following values
        + Values
            + `asc`
            + `desc`
            + `type,store`
            + `type,mfg`
    + redeemed (optional, boolean) ... set to `true` to retrieve a user's redeemed offers
        token must also be set. **clipped/expired must not be set** - sets redeemedDate JSON element for date redeemed (null otherwise)
    + expired (optional, boolean) ... set to `true` to retrieve a user's expired offers
        token must also be set. **clipped/redeemed must not be set**
    + includeClipped (optional, boolean) ... set to `false` to exclude clipped offers 
        overrides clipped

+ Response 200 (application/json)

            [
                {
                    "id": 40633,
                    "type": "mfg",
                    "badge": "",
                    "clipped": false,
                    "redeemedDate": null,
                    "category": {
                        "id": "c2ztS9Kuoz",
                        "name": "Grocery",
                        "active": 5,
                        "value": 300,
                        "key": "grocery"
                    },
                    "brand": "ConAgra Foods",
                    "description": "Save $0.75 on Hunt's Ketchup®. Offer redeemed with valid in-store purchase.",
                    "shortDescription": "Save $0.75 on Hunt's Ketchup®",
                    "imageUrl": "http://d17qf54098xvyo.cloudfront.net/INTEGRATION/imageserver/cecd82efed312f421b019730f7043376-69047-20141126-13462120150212101346_965231_0.jpg",
                    "value": 75,
                    "valueText": "save $0.75",
                    "terms": "LIMIT ONE COUPON REDEMPTION PER IN-STORE PURCHASE. ANY OTHER USE CONSTITUTES FRAUD. Void if sold, copied, transferred, altered, prohibited or restricted. Good only in the USA. CONSUMER: No other coupon may be used with this coupon. Consumer pays any sales tax and will not receive any credit or cash back if coupon value exceeds purchase price. Cash value of 1/20¢. ©INmart, Inc. All Rights Reserved.",
                    "minPurchase": "1",
                    "offerSortValue": "75",
                    "expirationDate":{
                        "__type":"Date",
                        "iso":"2014-07-31T00:00:00.000Z"
                    },
                    "clipStartDate":{
                        "__type":"Date",
                        "iso":"2014-06-05T00:00:00.000Z"
                    },
                    "clipEndDate":{
                        "__type":"Date",
                        "iso":"2014-06-30T00:00:00.000Z"
                    }
                }
            ]
            
+ Response 401

        Token is invalid

+ Response 500

        Some other error occurred, DPN service likely unavailable, or something was wrong with the parameters provided.
        
## Categories [/categories{?token}]

### Categories [GET]

`https://<api_url>/categories?<Optional Parameters>`

Include the user token to retrieve a customized list of categories, specific to that user.

+ Response 200 (application/json)

        [
            {
                "id": "c2ztS9Kuoz",
                "name": "Grocery",
                "active": 5,                    
                "value": 300,
                "key": "grocery"
            }
        ]
            
+ Response 500

        Some other error occurred, DPN service likely unavailable, or something was wrong with the parameters provided.
        
## Offer Clip [/offers/clip]

### Offer Clip [POST]

`https://<api_url>/offers/clip`

The Reset Password resource has the following (x-www-form-urlencoded) attributes:

- **token** : User login token (Required)
- **id** : offer id (Required)

+ Request (application/json)

        {
            "token": "XXXXXXXXXXXX",
            "id": "1"
        }
            
+ Response 200 (application/json)

        {
            "clipped": true,
            "clipped_count": 5,
            "clipped_value": 205,
            "nextOffer" : {
                    "id": 40633,
                    "type": "mfg",
                    "badge": "",
                    "clipped": false,
                    "redeemedDate": null,
                    "category": {
                        "id": "c2ztS9Kuoz",
                        "name": "Grocery",
                        "active": 5,
                        "value": 300,
                        "key": "grocery"
                    },
                    "brand": "ConAgra Foods",
                    "description": "Save $0.75 on Hunt's Ketchup®. Offer redeemed with valid in-store purchase.",
                    "shortDescription": "Save $0.75 on Hunt's Ketchup®",
                    "imageUrl": "http://d17qf54098xvyo.cloudfront.net/INTEGRATION/imageserver/cecd82efed312f421b019730f7043376-69047-20141126-13462120150212101346_965231_0.jpg",
                    "value": 75,
                    "valueText": "save $0.75",
                    "terms": "LIMIT ONE COUPON REDEMPTION PER IN-STORE PURCHASE. ANY OTHER USE CONSTITUTES FRAUD. Void if sold, copied, transferred, altered, prohibited or restricted. Good only in the USA. CONSUMER: No other coupon may be used with this coupon. Consumer pays any sales tax and will not receive any credit or cash back if coupon value exceeds purchase price. Cash value of 1/20¢. ©INmart, Inc. All Rights Reserved.",
                    "minPurchase": "1",
                    "offerSortValue": "75",
                    "expirationDate":{
                        "__type":"Date",
                        "iso":"2014-07-31T00:00:00.000Z"
                    },
                    "clipStartDate":{
                        "__type":"Date",
                        "iso":"2014-06-05T00:00:00.000Z"
                    },
                    "clipEndDate":{
                        "__type":"Date",
                        "iso":"2014-06-30T00:00:00.000Z"
                    }
                }
        }

+ Response 400

        Coupon ID is invalid

+ Response 401

        Token is invalid
        
+ Response 410

        Unrecoverable clip error, either the coupon is already in the wallet or there was a problem adding to the wallet
        
+ Response 500

        Some other error occurred, DPN service likely unavailable, or something was wrong with the parameters provided.
        
## Offer Recommend [/offers/recommend{?token,categories,keywords,limit}]

### Offer Recommend [GET]

`https://<api_url>/offers/recommend?<Optional Parameters>`

+ Parameters
    + token (optional, string) ... User login token
    + categories (optional, string, `baby,food`) ... a comma delimited list of category ids to return (from the category API), default is offers from all categories
    + keywords (optional, string, `baby,food`) ... a comma delimited list of keywords to search offers for
    + limit = `1` (optional, number)  ... limit to n number of reccomendations

+ Response 200 (application/json)

            [
                {
                    "id": 40633,
                    "type": "mfg",
                    "badge": "",
                    "clipped": false,
                    "redeemedDate": null,
                    "category": {
                        "id": "c2ztS9Kuoz",
                        "name": "Grocery",
                        "active": 5,
                        "value": 300,
                        "key": "grocery"
                    },
                    "brand": "ConAgra Foods",
                    "description": "Save $0.75 on Hunt's Ketchup®. Offer redeemed with valid in-store purchase.",
                    "shortDescription": "Save $0.75 on Hunt's Ketchup®",
                    "imageUrl": "http://d17qf54098xvyo.cloudfront.net/INTEGRATION/imageserver/cecd82efed312f421b019730f7043376-69047-20141126-13462120150212101346_965231_0.jpg",
                    "value": 75,
                    "valueText": "save $0.75",
                    "terms": "LIMIT ONE COUPON REDEMPTION PER IN-STORE PURCHASE. ANY OTHER USE CONSTITUTES FRAUD. Void if sold, copied, transferred, altered, prohibited or restricted. Good only in the USA. CONSUMER: No other coupon may be used with this coupon. Consumer pays any sales tax and will not receive any credit or cash back if coupon value exceeds purchase price. Cash value of 1/20¢. ©INmart, Inc. All Rights Reserved.",
                    "minPurchase": "1",
                    "offerSortValue": "75",
                    "expirationDate":{
                        "__type":"Date",
                        "iso":"2014-07-31T00:00:00.000Z"
                    },
                    "clipStartDate":{
                        "__type":"Date",
                        "iso":"2014-06-05T00:00:00.000Z"
                    },
                    "clipEndDate":{
                        "__type":"Date",
                        "iso":"2014-06-30T00:00:00.000Z"
                    }
                }
            ]

+ Response 500

        Some other error occurred, DPN service likely unavailable, or something was wrong with the parameters provided.

## Offer Keywords [/keywords]

### Offer Keywords [GET]

`https://<api_url>/keywords`
            
+ Response 200 (application/json)

        {
            "keywords" : [
                "nature",
                "valley",
                "granola",
                "bars",
                "betty",
                "crocker",
                "cookie"
            ]
        }
        
+ Response 500

        Some other error occurred, DPN service likely unavailable, or something was wrong with the parameters provided.
        